version: "3"

services:
  db:
    image: postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:$PORT --noreload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python manage.py migrate
  